#!/usr/bin/env python3
"""M5 fuse-family runner — the model-scale (compounding) arms, via one-shot
`fuse` driving the local LiteLLM gateway (openrouter/cloud + local models).

Arms (2x2, all within the SAME harness — never compared to claude-CLI arms):
  L   large model + shell tools          (codeindex tools disabled + shim)
  LX  large model + shell + codeindex    (native fuse tools + PATH wrapper)
  S   small model + shell tools          (codeindex tools disabled + shim)
  SX  small model + shell + codeindex    (native fuse tools + PATH wrapper)

The compound gate (pre-registered in tasks_m5.json header): SX must match L's
success on the dominate suite (index substitutes for model scale) AND beat S
(the index, not the small model, closes the gap).

Mechanics:
- Treatment arms put a `codeindex` WRAPPER on PATH that injects the repo root
  (fuse's native codeindex_* tools call `codeindex <sub> <symbol>` with no
  root; the current binary requires one).
- Control arms disable codeindex_impact/codeindex_callers via a repo-planted
  .fuse.local.yml (tighten-only merge honors disabled:), put the failing shim
  first on PATH, and set CODEINDEX_DISABLED=1.
- All arms disable write/web/agent/skill tools (.fuse.local.yml) — M5 tasks
  are read-only.
- Metrics come from the -trace file (REQ/RESP markers): turns = #REQ, tokens
  summed from per-RESP usage, answer = last RESP without tool_calls. The
  gateway reports no $ cost; tokens are the fuse-family cost proxy
  (cost_usd stays None).

Usage:
  python3 run_m5_fuse.py --smoke                  # 1 task/suite x 4 arms
  python3 run_m5_fuse.py --full
Flags: --arms L,LX,S,SX  --model-large glm  --model-small qwen3-coder
       --timeout 600  --tasks N  --seed
"""

from __future__ import annotations

import argparse
import json
import os
import random
import re
import subprocess
import sys
import time
from datetime import datetime, timezone
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent
BENCH = REPO_ROOT / "bench"
BIN = BENCH / "agent_ab" / ".bin" / "codeindex"
FUSE = Path.home() / "dev" / "fuse" / "fuse"
RESULTS = HERE / "results"
TRACES = RESULTS / "fuse_traces"
RUNS = RESULTS / "runs_m5_fuse.jsonl"
TASKS = HERE / "tasks" / "tasks_m5.json"

os.environ.setdefault("AB_WORK", str(BENCH / "repos"))
sys.path.insert(0, str(BENCH / "agent_ab"))
sys.path.insert(0, str(BENCH))
from run_ab import arm_a_shim_dir, git_reset  # noqa: E402
from build_tasks_m5 import repo_path  # noqa: E402

# tools disabled in EVERY fuse arm (read-only bench; no sub-agents/skills —
# they break turn/token accounting, same rationale as the claude-CLI family)
BASE_DISABLED = [
    "edit_file", "write_file", "web_search", "web_fetch", "spawn_agent",
    "skill", "pipeline_run", "ask_user", "blackboard_write",
    "blackboard_read", "blackboard_wait", "blackboard_keys",
    "blackboard_delete",
]
CODEINDEX_TOOLS = ["codeindex_impact", "codeindex_callers"]

MARKER = re.compile(r"── (\w+) \[([^\]]*)\] ──")

# Treatment note for index arms (LX/SX), prepended to the task prompt. The
# claude-CLI family's arm B gets an equivalent note from the shipped plugin;
# without one, a first fuse smoke measured ZERO adoption of the native
# codeindex tools by both glm and qwen3-coder (archived as
# runs_m5_fuse_nonote.jsonl.bak) — bare tools in the tool list are not a
# treatment. The treatment is tools + note, in both families.
INDEX_NOTE = (
    "Note: this repository has a prebuilt code index. The codeindex_callers "
    "tool returns every caller of a symbol (function name + file) directly, "
    "and codeindex_impact returns its blast radius (callers + callees). For "
    "'who calls X' / impact questions these one-call tools are usually "
    "cheaper and more complete than grep.\n\n"
)


def wrapper_dir() -> Path:
    d = HERE / ".fusewrap"
    d.mkdir(exist_ok=True)
    w = d / "codeindex"
    w.write_text(
        "#!/bin/sh\n"
        "# bench wrapper: fuse's codeindex tools omit the repo root the real\n"
        "# CLI requires; inject it from CODEINDEX_REPO.\n"
        'sub="$1"; shift\n'
        'exec "$CODEINDEX_REAL" "$sub" "$CODEINDEX_REPO" "$@"\n'
    )
    w.chmod(0o755)
    return d


def write_local_yml(repo: Path, with_codeindex: bool):
    disabled = list(BASE_DISABLED) + ([] if with_codeindex else CODEINDEX_TOOLS)
    lines = ["# generated by run_m5_fuse.py (git_reset removes it)",
             "permissions:",
             "  disabled: [" + ", ".join(disabled) + "]", ""]
    (repo / ".fuse.local.yml").write_text("\n".join(lines))


def parse_trace(path: Path) -> dict:
    """turns / tokens / answer / codeindex adoption from a fuse trace file."""
    raw = path.read_text() if path.exists() else ""
    parts = MARKER.split(raw)
    n_req = n_err = 0
    inp = out = 0
    answer = ""
    codeindex_calls = 0
    for i in range(1, len(parts) - 1, 3):
        kind, body = parts[i], parts[i + 2].strip()
        if kind == "REQ":
            n_req += 1
        elif kind == "ERROR":
            n_err += 1
        elif kind == "RESP":
            try:
                d = json.loads(body)
            except json.JSONDecodeError:
                continue
            u = d.get("usage") or {}
            inp += u.get("prompt_tokens", 0)
            out += u.get("completion_tokens", 0)
            msg = (d.get("choices") or [{}])[0].get("message", {})
            tcs = msg.get("tool_calls") or []
            for tc in tcs:
                fn = tc.get("function", {})
                name = fn.get("name", "")
                if name.startswith("codeindex"):
                    codeindex_calls += 1
                elif name == "bash" and "codeindex" in fn.get("arguments", "").lower():
                    codeindex_calls += 1
            if not tcs and msg.get("content"):
                answer = msg["content"]
    return {
        "num_turns": n_req, "n_gateway_errors": n_err,
        "input_tokens": inp, "output_tokens": out,
        "cache_creation_tokens": 0, "cache_read_tokens": 0,
        "processed_tokens": inp + out,
        "cost_usd": None,
        "answer": answer, "codeindex_calls": codeindex_calls,
        "has_result": bool(answer),
        "tool_calls": {},
        "is_error": n_err > 0 and not answer, "subtype": None,
    }


def run_one(task: dict, arm: str, rep: int, repo: Path, model: str,
            timeout: int) -> dict:
    with_ci = arm.endswith("X")
    prompt = task["prompt"].replace("{REPO_PATH}", str(repo))
    if with_ci:
        prompt = INDEX_NOTE + prompt
    key = f"{task['id']}_{arm}_r{rep}"
    TRACES.mkdir(parents=True, exist_ok=True)
    trace = TRACES / f"{key}.trace"

    write_local_yml(repo, with_codeindex=with_ci)
    env = dict(os.environ)
    if with_ci:
        env["PATH"] = f"{wrapper_dir()}{os.pathsep}{env.get('PATH', '')}"
        env["CODEINDEX_REAL"] = str(BIN)
        env["CODEINDEX_REPO"] = str(repo)
        env["CODEINDEX_BIN"] = str(wrapper_dir() / "codeindex")
        env.pop("CODEINDEX_DISABLED", None)
    else:
        env.pop("CODEINDEX_BIN", None)
        env["CODEINDEX_DISABLED"] = "1"
        env["PATH"] = f"{arm_a_shim_dir()}{os.pathsep}{env.get('PATH', '')}"

    cmd = [str(FUSE), "-model", model, "-approve-all", "-trace", str(trace),
           prompt]
    started = datetime.now(timezone.utc).isoformat()
    t0 = time.time()
    timed_out = False
    stderr_tail = ""
    try:
        proc = subprocess.run(cmd, cwd=str(repo), capture_output=True,
                              text=True, timeout=timeout, env=env)
        stderr_tail = proc.stderr[-500:]
    except subprocess.TimeoutExpired:
        timed_out = True
        stderr_tail = "TIMEOUT"
    dur = time.time() - t0

    metrics = parse_trace(trace)
    if timed_out:
        metrics["has_result"] = False
    return {
        "key": key, "task_id": task["id"], "type": task["type"],
        "suite": task["suite"], "repo": task["repo"], "arm": arm, "rep": rep,
        "model": model, "harness": "fuse",
        "started": started, "duration_s": round(dur, 1),
        "timed_out": timed_out, "stderr_tail": stderr_tail,
        "transcript": str(trace.relative_to(REPO_ROOT)),
        "hook_fires": 0,
        **metrics,
    }


def load_done(runs_file: Path) -> set:
    done = set()
    if runs_file.exists():
        for ln in runs_file.read_text().splitlines():
            try:
                done.add(json.loads(ln)["key"])
            except Exception:
                pass
    return done


def build_index(repo: Path):
    subprocess.run([str(BIN), "build", str(repo)], capture_output=True,
                   check=True)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--smoke", action="store_true")
    ap.add_argument("--full", action="store_true")
    ap.add_argument("--tasks", type=int, default=0)
    ap.add_argument("--arms", default="L,LX,S,SX")
    ap.add_argument("--reps", type=int, default=1)
    ap.add_argument("--model-large", default="glm")
    ap.add_argument("--model-small", default="qwen3-coder")
    ap.add_argument("--timeout", type=int, default=600)
    ap.add_argument("--seed", type=int, default=20260816)
    args = ap.parse_args()
    if not (args.smoke or args.full):
        args.smoke = True

    if not FUSE.exists():
        sys.exit(f"fuse binary missing: {FUSE} (make -C ~/dev/fuse build)")
    data = json.loads(TASKS.read_text())
    tasks = data["tasks"]
    arms = [a.strip() for a in args.arms.split(",") if a.strip()]

    if args.smoke:
        picked, seen = [], set()
        for t in tasks:
            if t["suite"] not in seen:
                seen.add(t["suite"])
                picked.append(t)
        tasks = picked
        print(f"SMOKE MODE: {len(tasks)} tasks x {len(arms)} arms x 1 rep")
    elif args.tasks:
        tasks = tasks[: args.tasks]

    used = {t["repo"] for t in tasks}
    repo_paths = {}
    for name in used:
        rp = repo_path(name)
        if not rp.exists():
            sys.exit(f"repo clone missing: {rp}")
        git_reset(rp)
        build_index(rp)
        repo_paths[name] = rp
    print(f"indexes built for: {sorted(used)}")

    matrix = [(t, a, r) for t in tasks for a in arms for r in range(args.reps)]
    random.Random(args.seed).shuffle(matrix)

    done = load_done(RUNS)
    RESULTS.mkdir(parents=True, exist_ok=True)
    ran = 0
    for task, arm, rep in matrix:
        key = f"{task['id']}_{arm}_r{rep}"
        if key in done:
            continue
        model = args.model_large if arm.startswith("L") else args.model_small
        rp = repo_paths[task["repo"]]
        git_reset(rp)
        print(f"  [{ran+1}] {key} model={model} ...", flush=True)
        row = run_one(task, arm, rep, rp, model, args.timeout)
        git_reset(rp)
        with open(RUNS, "a") as f:
            f.write(json.dumps(row) + "\n")
        print(f"       turns={row['num_turns']} tok={row['processed_tokens']} "
              f"codeindex_calls={row['codeindex_calls']} "
              f"answer_len={len(row.get('answer') or '')} "
              f"errors={row['n_gateway_errors']} "
              f"{'TIMEOUT' if row['timed_out'] else ''}")
        ran += 1

    print(f"\ndone: {ran} new runs -> {RUNS}")
    if args.smoke:
        print("Grade with: python3 grade_m5.py --family fuse; then "
              "gate_m5.py --fuse")


if __name__ == "__main__":
    main()
